#
# Module manifest for module 'AD-PowerAdmin_Honeypot'
#
# Generated by: CyberGladius
#
# Generated on: 2026-04-27
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'AD-PowerAdmin_Honeypot.psm1'

    # Version number of this module.
    ModuleVersion = '1.1'

    # ID used to uniquely identify this module
    GUID = 'b7e2a3c9-4f1d-4e8b-9a2c-5d0e7f3b1a84'

    # Author of this module
    Author = 'CyberGladius'

    # Company or vendor of this module
    CompanyName = 'CyberGladius.com'

    # Copyright statement for this module
    Copyright = '(c) 2026 CyberGladius. All rights reserved.'

    # Description of the functionality provided by this module
    Description = @'
    AD-PowerAdmin_Honeypot deploys and monitors a hardened Active Directory honeytoken user account
    for password spray and unauthorized credential-use detection.

    The module provisions a realistic-looking service account that should never authenticate.
    Any authentication attempt against the account is treated as a high-confidence indicator
    of password spraying, brute-force activity, credential stuffing, or attacker reconnaissance.

    Functions included:
    - Install-HoneypotAccount       Wizard: username selection, OU placement, full provisioning
    - Edit-HoneypotSettings         Post-install configuration wizard (audit, interval, SPN, mode)
    - Test-HoneytokenUserSafety     Validates no SPNs, delegation, or privileged memberships
    - Start-HoneypotMonitor         Unattended hourly monitor; emails alerts on detection
    - Show-HoneypotReport           Interactive log review with optional CSV export
    - Remove-HoneypotAccount        Clean, reversible decommissioning
'@

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Functions to export from this module.
    # IF YOU DO NOT EXPORT THE FUNCTIONS, THEN THE FUNCTIONS WILL NOT BE AVAILABLE TO THE MAIN SCRIPT.
    FunctionsToExport = @(
        'Install-HoneypotAccount',
        'Edit-HoneypotSettings',
        'Test-HoneytokenUserSafety',
        'Start-HoneypotMonitor',
        'Show-HoneypotReport',
        'Remove-HoneypotAccount',
        'Install-HoneypotDecentralized',
        'Remove-HoneypotDecentralized',
        'Show-HoneypotHelp',
        'Invoke-HoneypotDetectionTest'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport = @()

    # List of all files packaged with this module
    FileList = @('AD-PowerAdmin_Honeypot.psm1', 'AD-PowerAdmin_Honeypot.psd1')

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module.
            Tags = @('ActiveDirectory', 'Security', 'Honeypot', 'Honeytoken', 'Detection', 'PasswordSpray')

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Brets0150/AD-PowerAdmin'

            # Channel: Alpha, Beta, Production
            Channel = 'Production'

            # ReleaseNotes of this module
            ReleaseNotes = @'
            v1.0:
            - Initial release.
            - Install-HoneypotAccount: interactive provisioning wizard with curated username list.
            - Test-HoneytokenUserSafety: validates account hardening across six criteria.
            - Start-HoneypotMonitor: hourly unattended monitor across all domain controllers.
            - Show-HoneypotReport: interactive log review with configurable time range and CSV export.
            - Remove-HoneypotAccount: six-step reversible decommissioning workflow.

            v1.1:
            - Edit-HoneypotSettings: post-install configuration wizard for audit toggle, monitor
              interval (with scheduled task recreation), Kerberoasting SPN (with AD side effects),
              and monitor mode without removing and reinstalling the account.
            - Fixed Remove-HoneypotAccount not clearing HoneypotSPN from the settings file.
            - Set-HoneypotSettings: added MonitorMode parameter; added post-write SPN verification.
'@

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
