#
# Module manifest for module 'AD-PowerAdmin_HIBP_PwndPwMgr' Have I Been Pwned, Pwned Password Manager.
#
# Generated by: CyberGladius
#
# Generated on: 2024-08-24
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'AD-PowerAdmin_HIBP_PwndPwMgr.psm1'

    # Version number of this module.
    ModuleVersion = '1.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    # You need to generate a new GUID before publishing a new version of your module. New-Guid cmdlet can be used to generate a new GUID.
    GUID = '6b09b960-8299-44a7-9e33-880aa6fba6f4'
    # Author of this module
    Author = 'CyberGladius'

    # Company or vendor of this module
    CompanyName = 'CyberGladius.com'

    # Copyright statement for this module
    Copyright = '(c) 2024 CyberGladius. All rights reserved.'

    # Description of the functionality provided by this module
    Description = @'
    AD-PowerAdmin_HIBP_PwndPwMgr manages the Have I Been Pwned NTLM password hash database used by the AD password quality audit. It embeds a pure PowerShell 5.1 downloader with ETag-based incremental updates and parallel Start-Job workers -- no .NET SDK or external executables required.
'@

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Initialize-Module',
        'Start-HibpDownload',
        'Get-HibpPasswordHashesFiles',
        'Get-WeakPasswordsList',
        'Test-HibpToolsInstalled',
        'Uninstall-HibpTools',
        'Show-HibpTroubleshootingGuide'
    )
    # IF YOU DO NOT EXPORT THE FUNCTIONS, THEN THE FUNCTIONS WILL NOT BE AVAILABLE TO THE MAIN SCRIPT.

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList = @('AD-PowerAdmin_HIBP_PwndPwMgr.psm1', 'AD-PowerAdmin_HIBP_PwndPwMgr.psd1')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @()

            # A URL to the license for this module.
            # LicenseUri = 'https://github.com/Brets0150/AD-PowerAdmin'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Brets0150/AD-PowerAdmin'

            # A URL to an icon representing this module.
            # IconUri = ''

            # Channel: Alpha, Beta, Production
            Channel = 'Production'

            # ReleaseNotes of this module
            ReleaseNotes = @'
            v1.1 Production:
            - Promoted from Beta to Production. Pure PowerShell HIBP downloader validated
              through real-world operation. No functional changes from v1.1 Beta.
            v1.1 Beta:
            - Architectural change: replaced .NET SDK + haveibeenpwned-downloader.exe toolchain
              with an embedded pure PowerShell 5.1 downloader. No external installs required.
            - Added Start-HibpDownload: full-featured NTLM hash downloader with ETag-based
              incremental updates, parallel Start-Job workers, .part-file safety, and retry
              logic. Supports both directory mode and single-file mode.
            - Added 13 private helper functions adapted from Invoke-HibpPwnedPasswordsDownload
              v3.4: Initialize-HibpTls12, Resolve-HibpLocalPath, ConvertTo-HibpPrefix,
              Expand-HibpPrefixes, Get-HibpRangeUri, Get-HibpHeaderValue,
              Invoke-HibpRangeDownload, Test-HibpRangeFile, Import-HibpManifest,
              Export-HibpManifest, Split-HibpPrefixBuckets, Invoke-HibpDirectoryDownload,
              Invoke-HibpSingleFileDownload.
            - Removed Test-DotnetInstalled, Install-DotnetSdk, Install-HibpHashDownloader,
              Uninstall-DotnetSdk (no longer applicable without the .NET toolchain).
            - Changed Get-HibpPasswordHashesFiles: now a thin settings-aware wrapper around
              Start-HibpDownload; reads global:NtlmHashDataDir to select directory vs
              single-file mode; first-run detection via manifest presence.
            - Changed Test-HibpToolsInstalled: now checks API reachability via HttpWebRequest
              and whether local hash data has been downloaded.
            - Changed Uninstall-HibpTools: removes .NET artifact cleanup; now deletes hash
              data files only (file or directory per configured mode).
            - Changed Show-HibpTroubleshootingGuide: rewritten for pure-PS architecture;
              removed all .NET SDK content; added PS-native failure scenarios.
            - Changed Initialize-Module: removed HibpInstall submenu item; updated labels
              for HibpTest and HibpUninstall to reflect the new architecture.
            v1.0 Beta:
            - Rewrote Initialize-Module to register a single main-menu entry that opens a
              reusable submenu via Enter-SubMenu.
            - Added Test-HibpToolsInstalled: pre-flight check for dotnet and the exe.
            - Renamed Uninstall-DotNetSDK to Uninstall-DotnetSdk for naming consistency.
'@

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
