#
# Module manifest for module 'AD-PowerAdmin_PasswordsCtl'
#
# Generated by: CyberGladius
#
# Generated on: 2023-11-30
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'AD-PowerAdmin_PasswordsCtl.psm1'

    # Version number of this module.
    ModuleVersion = '3.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID = 'dd3ebe4d-f4f5-426c-8eca-22aecaaf53e3'
    # Author of this module
    Author = 'CyberGladius'

    # Company or vendor of this module
    CompanyName = 'CyberGladius.com'

    # Copyright statement for this module
    Copyright = '(c) 2023 CyberGladius. All rights reserved.'

    # Description of the functionality provided by this module
    Description = @'
    AD-PowerAdmin_PasswordsCtl manages password security for Active Directory.

    Capabilities:
    - KRBTGT password rotation with scheduled follow-up (Golden Ticket defense)
    - Breached and weak password audit using DSInternals and the HIBP NTLM hash database
    - User notification and enforcement workflow for compromised passwords
    - PasswordNotRequired (PASSWD_NOTREQD) flag audit and remediation
    - AS-REP Roasting (DoesNotRequirePreAuth) audit, risk rating, and remediation
'@

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Update-KRBTGTPassword',
        'Get-PasswordAudit',
        'Get-PasswordAuditAdminReport',
        'Test-PwUserFollowup',
        'Start-MonthlyPasswordAudit',
        'New-RandomPassword',
        'Test-NtlmHashesInDirectory',
        'Get-PasswordNotRequiredAccounts',
        'Get-PasswordNotRequiredAudit',
        'Show-PasswordNotRequiredFindings',
        'Start-PasswordNotRequiredRemediation',
        'Start-DailyPasswordNotRequiredAudit',
        'Get-AsRepRoastableAccounts',
        'Show-AsRepRoastingFindings',
        'Get-AsRepRoastingAudit',
        'Start-AsRepRoastingRemediation',
        'Start-DailyAsRepRoastingAudit'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
#    MainMenuItems = @('ADAdminAudit', 'ADSecurityBestPractices Test')

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList = @('AD-PowerAdmin_PasswordsCtl.psm1', 'AD-PowerAdmin_Examle.psd1')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @()

            # A URL to the license for this module.
            # LicenseUri = 'https://github.com/Brets0150/AD-PowerAdmin'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Brets0150/AD-PowerAdmin'

            # A URL to an icon representing this module.
            # IconUri = ''

            # Channel: Alpha, Beta, Production
            Channel = 'Production'

            # ReleaseNotes of this module
            ReleaseNotes = @'
            v1.0:
            - Migrate from old methods to new methods.
            v2.0:
            - Added PasswordNotRequired (PASSWD_NOTREQD) audit and remediation.
              New functions: Get-PasswordNotRequiredAccounts, Get-PasswordNotRequiredAudit,
              Show-PasswordNotRequiredFindings, Start-PasswordNotRequiredRemediation,
              Start-DailyPasswordNotRequiredAudit.
            - Two new sub-menu items added to Password Management: PasswordNotRequired Audit
              and PasswordNotRequired Remediation.
            - Daily unattended job Start-DailyPasswordNotRequiredAudit added; controlled by
              $global:PasswordNotRequiredAudit feature flag.
            v3.0:
            - Added AS-REP Roasting (DoesNotRequirePreAuth) audit and remediation.
              New functions: Get-AsRepRoastableAccounts, Show-AsRepRoastingFindings,
              Get-AsRepRoastingAudit, Start-AsRepRoastingRemediation,
              Start-DailyAsRepRoastingAudit.
            - Two new sub-menu items added to Password Management: AS-REP Roasting Audit
              and AS-REP Roasting Remediation.
            - Daily unattended job Start-DailyAsRepRoastingAudit added; controlled by
              $global:AsRepRoastingAudit feature flag.
            - Remediation design: re-enabling preauthentication does not invalidate captured
              hashes; manual password resets are required for all remediated accounts.
'@

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
