#
# Module manifest for module 'AD-PowerAdmin_Example'
#
# Generated by: CyberGladius
#
# Generated on: 2023-11-30
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'AD-PowerAdmin_Mgr.psm1'

    # Version number of this module.
    ModuleVersion = '1.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    # You need to generate a new GUID before publishing a new version of your module. New-Guid cmdlet can be used to generate a new GUID.
    GUID = 'f65d35a9-6895-4535-9349-be02c3dab26f'
    # Author of this module
    Author = 'CyberGladius'

    # Company or vendor of this module
    CompanyName = 'CyberGladius.com'

    # Copyright statement for this module
    Copyright = '(c) 2024 CyberGladius. All rights reserved.'

    # Description of the functionality provided by this module
    Description = @'
    AD-PowerAdmin_Mgr is a module that allows you to manage ad Accounts, Groups, and OUs.
'@

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Initialize-Module', 'Unregister-AdUser')
    # IF YOU DO NOT EXPORT THE FUNCTIONS, THEN THE FUNCTIONS WILL NOT BE AVAILABLE TO THE MAIN SCRIPT.

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList = @('AD-PowerAdmin_Mgr.psm1', 'AD-PowerAdmin_Mgr.psd1')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @()

            # A URL to the license for this module.
            # LicenseUri = 'https://github.com/Brets0150/AD-PowerAdmin'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Brets0150/AD-PowerAdmin'

            # A URL to an icon representing this module.
            # IconUri = ''

            # Channel: Alpha, Beta, Production
            Channel = 'Production'

            # ReleaseNotes of this module
            ReleaseNotes = @'
            v1.0:
            - Initial release, This module will be for managing AD Accounts, Groups, and OUs. Only the Unregister-AdUser function is available at this time.
            v1.1 Beta:
            - Added pre-flight validation to Unregister-AdUser. All required global variables
              (InactiveUsersLocations and each entry DisabledOULocal) are verified before any
              destructive AD operation is performed. Missing settings produce a clear error.
'@

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
